//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public int ClientID { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [Display(Name = "Mobile")]
        [StringLength(10, ErrorMessage = "Please enter a valid phone number", MinimumLength = 10)]
        public string ContactNumber { get; set; }

        [Required]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",
        ErrorMessage = "Sorry, The email address entered is not in the correct format. The standard email address format is name@example.com")]
        public string EmailAddress { get; set; }

        [Display(Name = "Physical Address")]
        public string PhysiclaAddress { get; set; }

        [Required]
        public string PreferedCommunicationChannel { get; set; }

        [Required]
        public int ProfileID { get; set; }
    }
} 