//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmailSetting
    {
        public int ProfileID { get; set; }

        [Required]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$",
        ErrorMessage = "Sorry, The email address entered is not in the correct format. The standard email address format is name@example.com")]
        public string Address { get; set; }

        [Required]
        public String Password { get; set; }

        [Required]
        public string Host { get; set; }

        [Required]
        public string Port { get; set; }

        [Required]
        [Display(Name = "Enable SSL")]
        public bool EnableSsl { get; set; }

        [Required]
        [Display(Name = "Delivery Method")]
        public string DeliveryMethod { get; set; }

        [Required]
        [Display(Name = "Use Defailt Credentials")]
        public bool UseDefailtCredentials { get; set; }
    }
}
