//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetting
    {
        public int ProfileID { get; set; }
        public string Address { get; set; }
        public byte[] Password { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public bool EnableSsl { get; set; }
        public string DeliveryMethod { get; set; }
        public bool UseDefailtCredentials { get; set; }
    }
}
