//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GeneralExpense : Expense
    {
        public int ProfileID { get; set; }

        [Required]
        public System.DateTime Date { get; set; }

        [Required]
        public decimal Amount { get; set; }

        [Required]
        public bool Repeat { get; set; }

        public byte[] Invoice_ReceiptCopy { get; set; }
    }
}
