//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralExpense
    {
        public int ProfileID { get; set; }
        public int ExpenseID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public bool Repeat { get; set; }
        public byte[] Invoice_ReceiptCopy { get; set; }
    }
}
