//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        public string InvoiceNum { get; set; }

        [Required]
        public System.DateTime DateTime { get; set; }

        [Required]
        public decimal SubTotal { get; set; }

        [Required]
        public decimal VAT { get; set; }


        public bool Paid { get; set; }
    }
}