//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelLog
    {
        public int ExpenseID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Reason { get; set; }
        public int OpeningKMs { get; set; }
        public Nullable<int> ClosingKMs { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> JobID { get; set; }
    }
}
