//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExpense
    {
        public string JobID { get; set; }
        public string ExpenseID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public byte[] Invoice_ReceiptCopy { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Job Job { get; set; }
    }
}
