USE [TaxApp]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[SP_MarkInvoiceAsPaid]
	@INum nchar(11)
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

    UPDATE [Invoice] 
	Set [Paid] = 1
    WHERE InvoiceNum = @INum

		COMMIT TRANSACTION 
	END TRY 
	BEGIN CATCH 
		IF @@TRANCOUNT > 0 
			ROLLBACK TRANSACTION
	END CATCH 
	END