USE [TaxApp]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[SP_MarkJobAsComplete]
	@JID int
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

    UPDATE [Jobs] 
	Set EndDate = GETDATE()
    WHERE JobID = @JID

		COMMIT TRANSACTION 
	END TRY 
	BEGIN CATCH 
		IF @@TRANCOUNT > 0 
			ROLLBACK TRANSACTION
	END CATCH 
	END